"""Autogenerate filtering for the enum CHECK constraints.

Alembic drops type-bound check constraints from the metadata side of a
comparison (`sqla_compat.all_table_check_constraints`) but still reflects them
from the database, so every enum-backed column looks like a constraint someone
removed. Left alone, the next autogenerated migration would helpfully offer to
drop the very constraints that make those columns safe.

These constraints belong to the `Enum` type, which creates and drops them along
with the column, so they are excluded from comparison by name.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic.runtime.environment import NameFilterParentNames, NameFilterType

from app.infrastructure.postgres.base import Base


def enum_constraint_names() -> frozenset[str]:
    """The constraint names SQLAlchemy derives from each mapped Enum type."""
    return frozenset(
        column.type.name
        for table in Base.metadata.tables.values()
        for column in table.columns
        if isinstance(column.type, sa.Enum) and column.type.name is not None
    )


def include_name(
    name: str | None,
    type_: NameFilterType,
    parent_names: NameFilterParentNames,
) -> bool:
    return not (type_ == "check_constraint" and name in enum_constraint_names())
