"""0007 — workout domain (§14.4, §19, §26.2, Q51, Q52, Q58)

The four tables a logged workout lands in.

The design decisions are enforced here rather than in the service, because a
rule the database does not know is a rule the next code path can forget:

- `uq_session_exercises_block` — one block per position in a session. Q58 keeps
  A-B-A as three blocks in the order performed, and two rows claiming the same
  position is an order nobody can read back.
- The four `= IS NULL` checks on `exercise_sets` — Q52 says a derived value
  travels with the version that produced it. A number nobody can reproduce is
  worse than no number, and a CHECK is cheaper than the review that would have
  to catch it every time.
- `fk_session_exercises_group_in_same_session` — a group is referenced together
  with the session it belongs to. It carries the type, the rounds and the
  ordering, so borrowing one from another workout would give an exercise a
  structure nobody performed.
- `uq_session_exercises_group_position` — two exercises cannot hold the same
  place in a group. Partial, so ungrouped blocks (the common case) do not
  collide on NULL.
- `ck_entity_sources_has_a_source` — a provenance row naming neither a message
  nor a batch records that something came from somewhere, which is not
  provenance (§26.2).

`entity_sources` is append-only: `workflow-worker` gets INSERT and SELECT and
no UPDATE, because history that can be edited answers "why does the database
say this" with whatever was most recently convenient.

Revision ID: 0007_workout_domain
Revises: 0006_training_sessions
Create Date: 2026-08-20 01:41:45.628610+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.config import load_settings
from app.infrastructure.postgres.provisioning import sync_service_roles

revision: str = "0007_workout_domain"
down_revision: str | None = "0006_training_sessions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_sources",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("message_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_role",
            sa.Enum(
                "created_from",
                "updated_from",
                "clarified_by",
                name="sourcerole",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "message_id IS NOT NULL OR message_batch_id IS NOT NULL",
            name="ck_entity_sources_has_a_source",
        ),
        sa.ForeignKeyConstraint(["message_batch_id"], ["message_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_entity_sources_batch", "entity_sources", ["message_batch_id"], unique=False)
    op.create_index(
        "ix_entity_sources_entity", "entity_sources", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_sources_message_id"), "entity_sources", ["message_id"], unique=False
    )
    op.create_table(
        "exercise_groups",
        sa.Column("training_session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "group_type",
            sa.Enum(
                "superset",
                "triset",
                "circuit",
                "complex",
                name="exercisegrouptype",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["training_session_id"], ["training_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("training_session_id", "block_index", name="uq_exercise_groups_block"),
        sa.UniqueConstraint("id", "training_session_id", name="uq_exercise_groups_id_session"),
    )
    op.create_index(
        op.f("ix_exercise_groups_training_session_id"),
        "exercise_groups",
        ["training_session_id"],
        unique=False,
    )
    op.create_table(
        "session_exercises",
        sa.Column("training_session_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_group_id", sa.Uuid(), nullable=True),
        sa.Column("position_in_group", sa.Integer(), nullable=True),
        sa.Column("exercise_block_index", sa.Integer(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "strength",
                "distance_activity",
                "timed_activity",
                "mixed_activity",
                "mobility",
                "other",
                name="activitytype",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("raw_effort", sa.Text(), nullable=True),
        sa.Column("normalized_rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "effort_method",
            sa.Enum(
                "explicit_rpe",
                "rir_mapped",
                "phrase_table",
                "unnormalized",
                name="effortmethod",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("effort_version", sa.String(length=64), nullable=True),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("expected_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_group_id", "training_session_id"],
            ["exercise_groups.id", "exercise_groups.training_session_id"],
            name="fk_session_exercises_group_in_same_session",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["training_session_id"], ["training_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "training_session_id", "exercise_block_index", name="uq_session_exercises_block"
        ),
    )
    op.create_index(
        "ix_session_exercises_block",
        "session_exercises",
        ["training_session_id", "exercise_block_index"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_exercises_exercise_id"), "session_exercises", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_exercises_training_session_id"),
        "session_exercises",
        ["training_session_id"],
        unique=False,
    )
    op.create_index(
        "uq_session_exercises_group_position",
        "session_exercises",
        ["exercise_group_id", "position_in_group"],
        unique=True,
        postgresql_where=sa.text("exercise_group_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "exercise_sets",
        sa.Column("session_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column(
            "set_type",
            sa.Enum(
                "warmup",
                "working",
                "backoff",
                "drop_set",
                "failure",
                "amrap",
                "other",
                name="settype",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("repetitions", sa.Integer(), nullable=True),
        sa.Column(
            "repetitions_provenance",
            sa.Enum(
                "explicit",
                "inherited",
                name="ck_exercise_sets_repetitions_provenance",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("load_kg", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column(
            "load_mode",
            sa.Enum(
                "total",
                "per_side",
                "per_implement",
                "bodyweight",
                "bodyweight_plus",
                "bodyweight_minus",
                name="loadmode",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column(
            "load_provenance",
            sa.Enum(
                "explicit",
                "inherited",
                name="ck_exercise_sets_load_provenance",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("raw_load_text", sa.String(length=64), nullable=True),
        sa.Column("distance_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "distance_provenance",
            sa.Enum(
                "explicit",
                "inherited",
                name="ck_exercise_sets_distance_provenance",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("duration_s", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "duration_provenance",
            sa.Enum(
                "explicit",
                "inherited",
                name="ck_exercise_sets_duration_provenance",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("raw_effort", sa.Text(), nullable=True),
        sa.Column("normalized_rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "effort_method",
            sa.Enum(
                "explicit_rpe",
                "rir_mapped",
                "phrase_table",
                "unnormalized",
                name="effortmethod",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("effort_version", sa.String(length=64), nullable=True),
        sa.Column("volume_kg", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("volume_metric_version", sa.String(length=64), nullable=True),
        sa.Column("estimated_one_rm_kg", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("one_rm_metric_version", sa.String(length=64), nullable=True),
        sa.Column("pace_s_per_km", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("pace_metric_version", sa.String(length=64), nullable=True),
        sa.Column("speed_m_s", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("speed_metric_version", sa.String(length=64), nullable=True),
        sa.Column("expected_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(estimated_one_rm_kg IS NULL) = (one_rm_metric_version IS NULL)",
            name="ck_exercise_sets_one_rm_versioned",
        ),
        sa.CheckConstraint(
            "(pace_s_per_km IS NULL) = (pace_metric_version IS NULL)",
            name="ck_exercise_sets_pace_versioned",
        ),
        sa.CheckConstraint(
            "(speed_m_s IS NULL) = (speed_metric_version IS NULL)",
            name="ck_exercise_sets_speed_versioned",
        ),
        sa.CheckConstraint(
            "(volume_kg IS NULL) = (volume_metric_version IS NULL)",
            name="ck_exercise_sets_volume_versioned",
        ),
        sa.ForeignKeyConstraint(
            ["session_exercise_id"], ["session_exercises.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_exercise_id", "set_index", name="uq_exercise_sets_index"),
    )
    op.create_index(
        op.f("ix_exercise_sets_session_exercise_id"),
        "exercise_sets",
        ["session_exercise_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Four new tables, and the grant policy is only converged if it is re-run
    # against them -- the same reason 0005 and 0006 end this way.
    sync_service_roles(op.get_bind(), load_settings())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercise_sets_session_exercise_id"), table_name="exercise_sets")
    op.drop_table("exercise_sets")
    op.drop_index(
        "uq_session_exercises_group_position",
        table_name="session_exercises",
        postgresql_where=sa.text("exercise_group_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_session_exercises_training_session_id"), table_name="session_exercises")
    op.drop_index(op.f("ix_session_exercises_exercise_id"), table_name="session_exercises")
    op.drop_index("ix_session_exercises_block", table_name="session_exercises")
    op.drop_table("session_exercises")
    op.drop_index(op.f("ix_exercise_groups_training_session_id"), table_name="exercise_groups")
    op.drop_table("exercise_groups")
    op.drop_index(op.f("ix_entity_sources_message_id"), table_name="entity_sources")
    op.drop_index("ix_entity_sources_entity", table_name="entity_sources")
    op.drop_index("ix_entity_sources_batch", table_name="entity_sources")
    op.drop_table("entity_sources")
    # ### end Alembic commands ###
