"""0008 — a note belongs to the set it describes

WS-6 put `notes` on `session_exercises` only, and WS-9 found the gap the moment
a real input went through: the contract accepts a note per set, and "esteira"
on one interval is a fact about that interval. Without this column the note
parsed cleanly and then vanished, which is the one thing this pipeline is not
allowed to do with something the user said.

No grant changes: `exercise_sets` is already writable by the one role that
writes it.

Revision ID: 0008_set_notes
Revises: 0007_workout_domain
Create Date: 2026-08-20 03:47:49.116814+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008_set_notes"
down_revision: str | None = "0007_workout_domain"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercise_sets", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercise_sets", "notes")
    # ### end Alembic commands ###
