"""The curated catalog (D1, §16).

Hand-written rather than imported. An imported catalog brings thousands of
names nobody validated, and this catalog is judged by one thing only: whether
it resolves what a Brazilian lifter actually types into WhatsApp. Forty entries
somebody chose beat four thousand nobody read.

Two rules the data must satisfy, both asserted by `tests/domain/test_catalog_data.py`:

* **No alias appears twice.** Seeded aliases are global, and the database
  refuses a duplicate, so an ambiguous word must simply not be an alias.
  `remada` is deliberately absent for that reason -- there are four of them.
* **Every exercise has a primary muscle**, or analysis in a later sprint has
  nothing to group by.
"""

from __future__ import annotations

from typing import Final

from app.domain.exercises.catalog import (
    ExerciseRelationType,
    SeedEquipment,
    SeedExercise,
    SeedMuscle,
    SeedRelation,
)
from app.domain.training.activities import ActivityType, LoadMode

#: The activity types the catalog covers. OTHER is deliberately absent: it
#: exists for activities that are *not* in the catalog, so an entry typed OTHER
#: would be a modelling failure rather than data.
SEEDED_ACTIVITY_TYPES: Final[frozenset[ActivityType]] = frozenset(
    {
        ActivityType.STRENGTH,
        ActivityType.DISTANCE_ACTIVITY,
        ActivityType.TIMED_ACTIVITY,
        ActivityType.MIXED_ACTIVITY,
        ActivityType.MOBILITY,
    }
)


SEED_MUSCLES: Final[tuple[SeedMuscle, ...]] = (
    SeedMuscle("peitoral", "Peitoral", "chest"),
    SeedMuscle("dorsal", "Dorsal", "back"),
    SeedMuscle("trapezio", "Trapézio", "back"),
    SeedMuscle("lombar", "Lombar", "back"),
    SeedMuscle("deltoide-anterior", "Deltoide anterior", "shoulders"),
    SeedMuscle("deltoide-lateral", "Deltoide lateral", "shoulders"),
    SeedMuscle("deltoide-posterior", "Deltoide posterior", "shoulders"),
    SeedMuscle("biceps", "Bíceps", "arms"),
    SeedMuscle("triceps", "Tríceps", "arms"),
    SeedMuscle("antebraco", "Antebraço", "arms"),
    SeedMuscle("quadriceps", "Quadríceps", "legs"),
    SeedMuscle("isquiotibiais", "Isquiotibiais", "legs"),
    SeedMuscle("gluteo", "Glúteo", "legs"),
    SeedMuscle("adutores", "Adutores", "legs"),
    SeedMuscle("panturrilha", "Panturrilha", "legs"),
    SeedMuscle("abdomen", "Abdômen", "core"),
    SeedMuscle("core", "Core", "core"),
    SeedMuscle("cardiovascular", "Sistema cardiovascular", "systemic"),
)


SEED_EQUIPMENT: Final[tuple[SeedEquipment, ...]] = (
    SeedEquipment("barra", "Barra", is_implement=False),
    SeedEquipment("halteres", "Halteres", is_implement=True),
    SeedEquipment("kettlebell", "Kettlebell", is_implement=True),
    SeedEquipment("maquina", "Máquina", is_implement=False),
    SeedEquipment("polia", "Polia", is_implement=False),
    SeedEquipment("banco", "Banco", is_implement=False),
    SeedEquipment("barra-fixa", "Barra fixa", is_implement=False),
    SeedEquipment("paralelas", "Paralelas", is_implement=False),
    SeedEquipment("peso-corporal", "Peso corporal", is_implement=False),
    SeedEquipment("esteira", "Esteira", is_implement=False),
    SeedEquipment("bicicleta", "Bicicleta", is_implement=False),
    SeedEquipment("corda", "Corda", is_implement=False),
)


CATALOG_SEED: Final[tuple[SeedExercise, ...]] = (
    # ---------------------------------------------------------------- chest
    SeedExercise(
        slug="supino-reto",
        canonical_name="Supino reto",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("peitoral",),
        secondary_muscles=("triceps", "deltoide-anterior"),
        equipment=("barra", "banco"),
        aliases_pt_br=("supino", "supino reto", "supino com barra"),
        aliases_en=("bench press", "flat bench press"),
    ),
    SeedExercise(
        slug="supino-inclinado",
        canonical_name="Supino inclinado",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("peitoral",),
        secondary_muscles=("deltoide-anterior", "triceps"),
        equipment=("barra", "banco"),
        aliases_pt_br=("supino inclinado", "inclinado"),
        aliases_en=("incline bench press",),
    ),
    SeedExercise(
        slug="supino-declinado",
        canonical_name="Supino declinado",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("peitoral",),
        secondary_muscles=("triceps",),
        equipment=("barra", "banco"),
        aliases_pt_br=("supino declinado", "declinado"),
        aliases_en=("decline bench press",),
    ),
    SeedExercise(
        slug="supino-halteres",
        canonical_name="Supino com halteres",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("peitoral",),
        secondary_muscles=("triceps", "deltoide-anterior"),
        equipment=("halteres", "banco"),
        aliases_pt_br=("supino com halteres", "supino halteres"),
        aliases_en=("dumbbell bench press",),
    ),
    SeedExercise(
        slug="crucifixo",
        canonical_name="Crucifixo",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("peitoral",),
        secondary_muscles=("deltoide-anterior",),
        equipment=("halteres", "banco"),
        aliases_pt_br=("crucifixo", "crucifixo reto"),
        aliases_en=("dumbbell fly", "chest fly"),
    ),
    SeedExercise(
        slug="flexao-de-braco",
        canonical_name="Flexão de braço",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("peitoral",),
        secondary_muscles=("triceps", "deltoide-anterior"),
        stabilizer_muscles=("core",),
        equipment=("peso-corporal",),
        aliases_pt_br=("flexão", "flexao", "flexões", "flexão de braço", "apoio"),
        aliases_en=("push-up", "push up", "pushup"),
    ),
    # ----------------------------------------------------------------- legs
    SeedExercise(
        slug="agachamento-livre",
        canonical_name="Agachamento livre",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("quadriceps",),
        secondary_muscles=("gluteo", "isquiotibiais"),
        stabilizer_muscles=("core", "lombar"),
        equipment=("barra",),
        aliases_pt_br=("agachamento", "agachamentos", "agachamento livre", "agacho"),
        aliases_en=("squat", "back squat"),
    ),
    SeedExercise(
        slug="agachamento-frontal",
        canonical_name="Agachamento frontal",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("quadriceps",),
        secondary_muscles=("gluteo",),
        stabilizer_muscles=("core",),
        equipment=("barra",),
        aliases_pt_br=("agachamento frontal",),
        aliases_en=("front squat",),
    ),
    SeedExercise(
        slug="leg-press",
        canonical_name="Leg press",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("quadriceps",),
        secondary_muscles=("gluteo",),
        equipment=("maquina",),
        aliases_pt_br=("leg press", "leg"),
        aliases_en=("leg press machine",),
    ),
    SeedExercise(
        slug="cadeira-extensora",
        canonical_name="Cadeira extensora",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("quadriceps",),
        equipment=("maquina",),
        aliases_pt_br=("cadeira extensora", "extensora"),
        aliases_en=("leg extension",),
    ),
    SeedExercise(
        slug="mesa-flexora",
        canonical_name="Mesa flexora",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("isquiotibiais",),
        equipment=("maquina",),
        aliases_pt_br=("mesa flexora", "flexora"),
        aliases_en=("leg curl", "lying leg curl"),
    ),
    SeedExercise(
        slug="afundo",
        canonical_name="Afundo",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("quadriceps",),
        secondary_muscles=("gluteo",),
        stabilizer_muscles=("core",),
        equipment=("halteres",),
        aliases_pt_br=("afundo", "afundos", "avanço"),
        aliases_en=("lunge", "walking lunge"),
    ),
    SeedExercise(
        slug="levantamento-terra",
        canonical_name="Levantamento terra",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("isquiotibiais", "gluteo"),
        secondary_muscles=("lombar", "dorsal", "trapezio"),
        stabilizer_muscles=("core",),
        equipment=("barra",),
        aliases_pt_br=("levantamento terra", "terra"),
        aliases_en=("deadlift", "conventional deadlift"),
    ),
    SeedExercise(
        slug="terra-romeno",
        canonical_name="Levantamento terra romeno",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("isquiotibiais",),
        secondary_muscles=("gluteo", "lombar"),
        equipment=("barra",),
        aliases_pt_br=("terra romeno", "stiff", "levantamento terra romeno"),
        aliases_en=("romanian deadlift", "rdl"),
    ),
    SeedExercise(
        slug="elevacao-pelvica",
        canonical_name="Elevação pélvica",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("gluteo",),
        secondary_muscles=("isquiotibiais",),
        equipment=("barra", "banco"),
        aliases_pt_br=("elevação pélvica", "elevacao pelvica"),
        aliases_en=("hip thrust",),
    ),
    SeedExercise(
        slug="cadeira-adutora",
        canonical_name="Cadeira adutora",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("adutores",),
        equipment=("maquina",),
        aliases_pt_br=("cadeira adutora", "adutora"),
        aliases_en=("hip adduction machine",),
    ),
    SeedExercise(
        slug="panturrilha-em-pe",
        canonical_name="Panturrilha em pé",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("panturrilha",),
        equipment=("maquina",),
        aliases_pt_br=("panturrilha", "panturrilha em pé", "gemeos"),
        aliases_en=("standing calf raise", "calf raise"),
    ),
    # ----------------------------------------------------------------- back
    SeedExercise(
        slug="remada-curvada",
        canonical_name="Remada curvada",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("dorsal",),
        secondary_muscles=("biceps", "trapezio"),
        stabilizer_muscles=("lombar",),
        equipment=("barra",),
        aliases_pt_br=("remada curvada",),
        aliases_en=("bent over row", "barbell row"),
    ),
    SeedExercise(
        slug="remada-unilateral",
        canonical_name="Remada unilateral",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("dorsal",),
        secondary_muscles=("biceps",),
        equipment=("halteres", "banco"),
        aliases_pt_br=("remada unilateral", "serrote"),
        aliases_en=("one arm dumbbell row", "single arm row"),
    ),
    SeedExercise(
        slug="remada-baixa",
        canonical_name="Remada baixa",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("dorsal",),
        secondary_muscles=("biceps", "trapezio"),
        equipment=("polia", "maquina"),
        aliases_pt_br=("remada baixa", "remada sentada"),
        aliases_en=("seated cable row",),
    ),
    SeedExercise(
        slug="puxada-frente",
        canonical_name="Puxada frente",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("dorsal",),
        secondary_muscles=("biceps",),
        equipment=("polia", "maquina"),
        aliases_pt_br=("puxada", "puxada frente", "pulley frente"),
        aliases_en=("lat pulldown", "pulldown"),
    ),
    SeedExercise(
        slug="barra-fixa",
        canonical_name="Barra fixa",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("dorsal",),
        secondary_muscles=("biceps",),
        equipment=("barra-fixa", "peso-corporal"),
        # "barra" alone is deliberately absent: in a Brazilian gym it means the
        # barbell, not the pull-up bar, and an alias that resolves the wrong
        # exercise silently is the worst failure this catalog can have.
        aliases_pt_br=("barra fixa", "barras"),
        aliases_en=("pull-up", "pull up", "pullup", "chin-up"),
    ),
    SeedExercise(
        slug="encolhimento",
        canonical_name="Encolhimento",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("trapezio",),
        equipment=("halteres",),
        aliases_pt_br=("encolhimento",),
        aliases_en=("shrug", "dumbbell shrug"),
    ),
    SeedExercise(
        slug="face-pull",
        canonical_name="Face pull",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("deltoide-posterior",),
        secondary_muscles=("trapezio",),
        equipment=("polia",),
        aliases_pt_br=("face pull", "puxada para o rosto"),
        aliases_en=("facepull",),
    ),
    # ------------------------------------------------------------- shoulders
    SeedExercise(
        slug="desenvolvimento-barra",
        canonical_name="Desenvolvimento com barra",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("deltoide-anterior",),
        secondary_muscles=("triceps", "deltoide-lateral"),
        stabilizer_muscles=("core",),
        equipment=("barra",),
        aliases_pt_br=("desenvolvimento", "desenvolvimento com barra"),
        aliases_en=("overhead press", "military press"),
    ),
    SeedExercise(
        slug="desenvolvimento-halteres",
        canonical_name="Desenvolvimento com halteres",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("deltoide-anterior",),
        secondary_muscles=("triceps", "deltoide-lateral"),
        equipment=("halteres",),
        aliases_pt_br=("desenvolvimento com halteres", "desenvolvimento halteres"),
        aliases_en=("dumbbell shoulder press",),
    ),
    SeedExercise(
        slug="elevacao-lateral",
        canonical_name="Elevação lateral",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("deltoide-lateral",),
        equipment=("halteres",),
        aliases_pt_br=("elevação lateral", "elevacao lateral", "lateral"),
        aliases_en=("lateral raise", "side raise"),
    ),
    SeedExercise(
        slug="elevacao-frontal",
        canonical_name="Elevação frontal",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("deltoide-anterior",),
        equipment=("halteres",),
        aliases_pt_br=("elevação frontal", "elevacao frontal"),
        aliases_en=("front raise",),
    ),
    SeedExercise(
        slug="crucifixo-inverso",
        canonical_name="Crucifixo inverso",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("deltoide-posterior",),
        secondary_muscles=("trapezio",),
        equipment=("halteres",),
        aliases_pt_br=("crucifixo inverso", "voador inverso"),
        aliases_en=("reverse fly", "rear delt fly"),
    ),
    # ------------------------------------------------------------------ arms
    SeedExercise(
        slug="rosca-direta",
        canonical_name="Rosca direta",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("biceps",),
        secondary_muscles=("antebraco",),
        equipment=("barra",),
        aliases_pt_br=("rosca direta", "rosca"),
        aliases_en=("barbell curl", "biceps curl"),
    ),
    SeedExercise(
        slug="rosca-alternada",
        canonical_name="Rosca alternada",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("biceps",),
        equipment=("halteres",),
        aliases_pt_br=("rosca alternada",),
        aliases_en=("alternating dumbbell curl",),
    ),
    SeedExercise(
        slug="rosca-martelo",
        canonical_name="Rosca martelo",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("biceps",),
        secondary_muscles=("antebraco",),
        equipment=("halteres",),
        aliases_pt_br=("rosca martelo", "martelo"),
        aliases_en=("hammer curl",),
    ),
    SeedExercise(
        slug="triceps-pulley",
        canonical_name="Tríceps pulley",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("triceps",),
        equipment=("polia",),
        aliases_pt_br=("tríceps pulley", "triceps pulley", "tríceps corda"),
        aliases_en=("triceps pushdown", "cable pushdown"),
    ),
    SeedExercise(
        slug="triceps-testa",
        canonical_name="Tríceps testa",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.TOTAL,
        is_bodyweight=False,
        primary_muscles=("triceps",),
        equipment=("barra", "banco"),
        aliases_pt_br=("tríceps testa", "triceps testa"),
        aliases_en=("skull crusher", "lying triceps extension"),
    ),
    SeedExercise(
        slug="mergulho-paralelas",
        canonical_name="Mergulho nas paralelas",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("triceps",),
        secondary_muscles=("peitoral", "deltoide-anterior"),
        equipment=("paralelas", "peso-corporal"),
        aliases_pt_br=("mergulho", "mergulhos", "paralelas", "mergulho nas paralelas"),
        aliases_en=("dip", "dips", "parallel bar dip"),
    ),
    # ------------------------------------------------------------------ core
    SeedExercise(
        slug="abdominal-supra",
        canonical_name="Abdominal supra",
        activity_type=ActivityType.STRENGTH,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("abdomen",),
        equipment=("peso-corporal",),
        aliases_pt_br=("abdominal", "abdominais", "abdominal supra"),
        aliases_en=("crunch", "sit-up"),
    ),
    SeedExercise(
        slug="prancha",
        canonical_name="Prancha",
        activity_type=ActivityType.TIMED_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("core",),
        secondary_muscles=("abdomen",),
        equipment=("peso-corporal",),
        aliases_pt_br=("prancha", "prancha isométrica"),
        aliases_en=("plank",),
    ),
    # ------------------------------------------------------- distance / timed
    SeedExercise(
        slug="corrida",
        canonical_name="Corrida",
        activity_type=ActivityType.DISTANCE_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("cardiovascular",),
        secondary_muscles=("quadriceps", "panturrilha"),
        equipment=("peso-corporal",),
        aliases_pt_br=("corrida", "correr"),
        aliases_en=("running", "run"),
    ),
    SeedExercise(
        slug="corrida-esteira",
        canonical_name="Corrida na esteira",
        activity_type=ActivityType.DISTANCE_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("cardiovascular",),
        secondary_muscles=("quadriceps",),
        equipment=("esteira",),
        aliases_pt_br=("esteira", "corrida na esteira"),
        aliases_en=("treadmill run", "treadmill"),
    ),
    SeedExercise(
        slug="caminhada",
        canonical_name="Caminhada",
        activity_type=ActivityType.DISTANCE_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("cardiovascular",),
        equipment=("peso-corporal",),
        aliases_pt_br=("caminhada", "caminhar"),
        aliases_en=("walking", "walk"),
    ),
    SeedExercise(
        slug="ciclismo",
        canonical_name="Ciclismo",
        activity_type=ActivityType.DISTANCE_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("cardiovascular",),
        secondary_muscles=("quadriceps",),
        equipment=("bicicleta",),
        aliases_pt_br=("ciclismo", "pedalar", "bike"),
        aliases_en=("cycling", "bike ride"),
    ),
    SeedExercise(
        slug="bicicleta-ergometrica",
        canonical_name="Bicicleta ergométrica",
        activity_type=ActivityType.DISTANCE_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("cardiovascular",),
        equipment=("bicicleta",),
        aliases_pt_br=("bicicleta ergométrica", "ergométrica", "spinning"),
        aliases_en=("stationary bike", "exercise bike"),
    ),
    SeedExercise(
        slug="pular-corda",
        canonical_name="Pular corda",
        activity_type=ActivityType.TIMED_ACTIVITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("cardiovascular",),
        secondary_muscles=("panturrilha",),
        equipment=("corda",),
        # Not "corda": it collides with the rope attachment in "tríceps corda".
        aliases_pt_br=("pular corda",),
        aliases_en=("jump rope", "skipping"),
    ),
    # -------------------------------------------------------- mixed/mobility
    SeedExercise(
        slug="caminhada-do-fazendeiro",
        canonical_name="Caminhada do fazendeiro",
        activity_type=ActivityType.MIXED_ACTIVITY,
        default_load_mode=LoadMode.PER_IMPLEMENT,
        is_bodyweight=False,
        primary_muscles=("antebraco", "trapezio"),
        stabilizer_muscles=("core",),
        equipment=("halteres", "kettlebell"),
        aliases_pt_br=("caminhada do fazendeiro",),
        aliases_en=("farmer's walk", "farmers walk", "farmer carry"),
    ),
    SeedExercise(
        slug="alongamento",
        canonical_name="Alongamento",
        activity_type=ActivityType.MOBILITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("core",),
        equipment=("peso-corporal",),
        aliases_pt_br=("alongamento", "alongar"),
        aliases_en=("stretching", "mobility"),
    ),
    SeedExercise(
        slug="mobilidade-quadril",
        canonical_name="Mobilidade de quadril",
        activity_type=ActivityType.MOBILITY,
        default_load_mode=LoadMode.BODYWEIGHT,
        is_bodyweight=True,
        primary_muscles=("gluteo",),
        equipment=("peso-corporal",),
        aliases_pt_br=("mobilidade de quadril", "mobilidade quadril"),
        aliases_en=("hip mobility",),
    ),
)


SEED_RELATIONS: Final[tuple[SeedRelation, ...]] = (
    SeedRelation("supino-inclinado", "supino-reto", ExerciseRelationType.VARIATION_OF),
    SeedRelation("supino-declinado", "supino-reto", ExerciseRelationType.VARIATION_OF),
    SeedRelation("supino-halteres", "supino-reto", ExerciseRelationType.VARIATION_OF),
    SeedRelation("supino-halteres", "supino-reto", ExerciseRelationType.SUBSTITUTE_FOR),
    SeedRelation("flexao-de-braco", "supino-reto", ExerciseRelationType.REGRESSION_OF),
    SeedRelation("agachamento-frontal", "agachamento-livre", ExerciseRelationType.VARIATION_OF),
    SeedRelation("leg-press", "agachamento-livre", ExerciseRelationType.SUBSTITUTE_FOR),
    SeedRelation("terra-romeno", "levantamento-terra", ExerciseRelationType.VARIATION_OF),
    SeedRelation("remada-unilateral", "remada-curvada", ExerciseRelationType.VARIATION_OF),
    SeedRelation("remada-baixa", "remada-curvada", ExerciseRelationType.SIMILAR_MOVEMENT),
    SeedRelation("puxada-frente", "barra-fixa", ExerciseRelationType.REGRESSION_OF),
    SeedRelation("barra-fixa", "puxada-frente", ExerciseRelationType.PROGRESSION_OF),
    SeedRelation(
        "desenvolvimento-halteres", "desenvolvimento-barra", ExerciseRelationType.VARIATION_OF
    ),
    SeedRelation("rosca-martelo", "rosca-direta", ExerciseRelationType.VARIATION_OF),
    SeedRelation("rosca-alternada", "rosca-direta", ExerciseRelationType.VARIATION_OF),
    SeedRelation("triceps-testa", "triceps-pulley", ExerciseRelationType.SIMILAR_MOVEMENT),
    SeedRelation("corrida-esteira", "corrida", ExerciseRelationType.VARIATION_OF),
    SeedRelation("caminhada", "corrida", ExerciseRelationType.REGRESSION_OF),
    SeedRelation("bicicleta-ergometrica", "ciclismo", ExerciseRelationType.VARIATION_OF),
)
